AWSTemplateFormatVersion: '2010-09-09'
Description: Member Account - Create IAM Role for Support Case Insights

Parameters:
  MasterAccountID:
    Type: String
    Description: The AWS Account ID of the master account.

Resources:
  CentralUserSupportCaseInsightsRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: CentralUserSupportCaseInsightsRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::${MasterAccountID}:user/support_case_insights'
            Action: sts:AssumeRole
      Policies:
        - PolicyName: SupportCaseAccessPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: 'support:*'
                Resource: '*'
